import type { Metadata } from "next";
import { SITE } from "@/lib/constants";

// ─── Shared keyword bank ─────────────────────────────────────────────────────
export const KEYWORDS = [
  // ── Brand ──
  "Vinay Interiors", "Vinay Interiors Hyderabad", "Vinay Atelier", "Vinay Interiors reviews",
  "Vinay Interiors Gachibowli", "Vinay Interiors Madhapur", "Vinay Interiors HITEC City",
  "Vinay Interiors contact", "Vinay Interiors portfolio", "Vinay Interiors projects",
  "Vinay Interiors modular kitchen", "Vinay Interiors wardrobe", "Vinay Interiors false ceiling",
  "Vinay Interiors office interior", "Vinay Interiors home automation",

  // ── Generic city-level intent ──
  "interior designer Hyderabad", "interior design Hyderabad",
  "best interior designer Hyderabad", "top interior designers Hyderabad",
  "interior designer near me Hyderabad", "interior design company Hyderabad",
  "home interior design Hyderabad", "luxury interior design Hyderabad",
  "premium interior design Hyderabad", "turnkey interior design Hyderabad",
  "residential interior design Hyderabad", "commercial interior design Hyderabad",
  "office interior design Hyderabad", "renovation services Hyderabad",
  "architecture firm Hyderabad", "interior design studio Hyderabad",
  "affordable interior designer Hyderabad", "low cost interior design Hyderabad",
  "best interior design firm Hyderabad", "award winning interior designer Hyderabad",
  "2BHK interior design Hyderabad", "3BHK interior design Hyderabad",
  "4BHK interior design Hyderabad", "villa interior design Hyderabad",
  "apartment interior design Hyderabad", "flat interior design Hyderabad",
  "duplex interior design Hyderabad", "penthouse interior design Hyderabad",
  "interior design consultation Hyderabad", "free interior design consultation Hyderabad",
  "interior design quote Hyderabad", "interior design cost Hyderabad",
  "interior design price Hyderabad", "interior designer Hyderabad price list",
  "top 10 interior designers Hyderabad", "best interior design company Hyderabad",
  "interior designer Hyderabad Telangana", "interior design Hyderabad Telangana",
  "interior design Telangana", "premium interior design Telangana",
  "interior design studio Hyderabad", "bespoke interior design Hyderabad",
  "contemporary interior design Hyderabad", "modern interior design Hyderabad",
  "luxury home interior Hyderabad", "home decor Hyderabad",
  "home renovation contractor Hyderabad", "full home renovation Hyderabad",
  "turnkey interior designer Hyderabad", "end to end interior design Hyderabad",
  "interior designer Hyderabad 2024", "interior designer Hyderabad 2025",

  // ════════════════════════════════════════════════════════════════════════════
  // ── NANAKARAMGUDA ──
  // ════════════════════════════════════════════════════════════════════════════
  "interior designer Nanakaramguda", "interior design Nanakaramguda",
  "best interior designer Nanakaramguda", "top interior designer Nanakaramguda",
  "interior designer near me Nanakaramguda", "interior design company Nanakaramguda",
  "home interior design Nanakaramguda", "luxury interior design Nanakaramguda",
  "premium interior design Nanakaramguda", "turnkey interior design Nanakaramguda",
  "residential interior designer Nanakaramguda", "commercial interior designer Nanakaramguda",
  "office interior design Nanakaramguda", "apartment interior design Nanakaramguda",
  "2BHK interior design Nanakaramguda", "3BHK interior design Nanakaramguda",
  "villa interior design Nanakaramguda", "flat interior design Nanakaramguda",
  "modular kitchen Nanakaramguda", "modular kitchen designer Nanakaramguda",
  "kitchen design Nanakaramguda", "kitchen renovation Nanakaramguda",
  "false ceiling Nanakaramguda", "gypsum ceiling Nanakaramguda", "POP ceiling Nanakaramguda",
  "false ceiling designer Nanakaramguda", "ceiling design Nanakaramguda",
  "wardrobe designer Nanakaramguda", "walk-in wardrobe Nanakaramguda",
  "cupboard design Nanakaramguda", "built-in wardrobe Nanakaramguda",
  "home automation Nanakaramguda", "smart home Nanakaramguda",
  "home theater Nanakaramguda", "home theater design Nanakaramguda",
  "main door design Nanakaramguda", "main door elevation Nanakaramguda",
  "full home renovation Nanakaramguda", "home renovation Nanakaramguda",
  "interior design consultation Nanakaramguda", "free consultation interior design Nanakaramguda",
  "interior designer Nanakramguda", "interior design Nanakramguda",
  "best interior design Nanakaramguda", "interior decorator Nanakaramguda",
  "interior design studio Nanakaramguda", "renovation contractor Nanakaramguda",
  "3D interior design Nanakaramguda", "interior design price Nanakaramguda",

  // ════════════════════════════════════════════════════════════════════════════
  // ── FINANCIAL DISTRICT ──
  // ════════════════════════════════════════════════════════════════════════════
  "interior designer Financial District", "interior design Financial District",
  "interior designer Financial District Hyderabad", "interior design Financial District Hyderabad",
  "best interior designer Financial District", "top interior designer Financial District Hyderabad",
  "interior designer near me Financial District Hyderabad",
  "office interior design Financial District", "office interior design Financial District Hyderabad",
  "commercial interior designer Financial District", "commercial interior design Financial District",
  "corporate interior design Financial District Hyderabad",
  "home interior design Financial District Hyderabad",
  "residential interior designer Financial District Hyderabad",
  "apartment interior design Financial District", "luxury apartment interior Financial District",
  "2BHK interior design Financial District", "3BHK interior design Financial District",
  "villa interior design Financial District Hyderabad",
  "modular kitchen Financial District", "modular kitchen designer Financial District Hyderabad",
  "kitchen design Financial District", "kitchen renovation Financial District",
  "false ceiling Financial District", "gypsum ceiling Financial District",
  "false ceiling designer Financial District Hyderabad", "POP ceiling Financial District",
  "wardrobe designer Financial District", "walk-in wardrobe Financial District Hyderabad",
  "cupboard design Financial District", "built-in wardrobe Financial District",
  "home automation Financial District", "smart home Financial District Hyderabad",
  "home theater Financial District", "home theater design Financial District",
  "main door design Financial District", "main door elevation Financial District",
  "full home renovation Financial District", "home renovation Financial District Hyderabad",
  "interior design consultation Financial District", "free consultation interior designer Financial District",
  "interior decorator Financial District Hyderabad", "interior design studio Financial District",
  "turnkey interior design Financial District", "renovation contractor Financial District",
  "3D interior design Financial District", "interior design company Financial District Hyderabad",
  "premium interior design Financial District", "luxury interior design Financial District",
  "best interior design company Financial District Hyderabad",

  // ════════════════════════════════════════════════════════════════════════════
  // ── TELLAPUR ──
  // ════════════════════════════════════════════════════════════════════════════
  "interior designer Tellapur", "interior design Tellapur",
  "best interior designer Tellapur", "top interior designer Tellapur",
  "interior designer near me Tellapur", "interior design company Tellapur",
  "home interior design Tellapur", "luxury interior design Tellapur",
  "premium interior design Tellapur", "turnkey interior design Tellapur",
  "residential interior designer Tellapur", "commercial interior designer Tellapur",
  "office interior design Tellapur", "apartment interior design Tellapur",
  "2BHK interior design Tellapur", "3BHK interior design Tellapur",
  "villa interior design Tellapur", "flat interior design Tellapur",
  "modular kitchen Tellapur", "modular kitchen designer Tellapur",
  "kitchen design Tellapur", "kitchen renovation Tellapur",
  "false ceiling Tellapur", "gypsum ceiling Tellapur", "POP ceiling Tellapur",
  "false ceiling designer Tellapur", "ceiling design Tellapur",
  "wardrobe designer Tellapur", "walk-in wardrobe Tellapur",
  "cupboard design Tellapur", "built-in wardrobe Tellapur",
  "home automation Tellapur", "smart home Tellapur",
  "home theater Tellapur", "home theater design Tellapur",
  "main door design Tellapur", "main door elevation Tellapur",
  "full home renovation Tellapur", "home renovation Tellapur",
  "interior design consultation Tellapur", "free consultation interior design Tellapur",
  "interior decorator Tellapur", "interior design studio Tellapur",
  "renovation contractor Tellapur", "3D interior design Tellapur",
  "interior design price Tellapur", "best interior design Tellapur",

  // ════════════════════════════════════════════════════════════════════════════
  // ── GACHIBOWLI ──
  // ════════════════════════════════════════════════════════════════════════════
  "interior designer Gachibowli", "interior design Gachibowli",
  "best interior designer Gachibowli", "top interior designer Gachibowli",
  "interior designer near me Gachibowli", "interior design company Gachibowli",
  "home interior design Gachibowli", "luxury interior design Gachibowli",
  "premium interior design Gachibowli", "turnkey interior design Gachibowli",
  "residential interior designer Gachibowli", "commercial interior designer Gachibowli",
  "office interior design Gachibowli", "apartment interior design Gachibowli",
  "2BHK interior design Gachibowli", "3BHK interior design Gachibowli",
  "4BHK interior design Gachibowli", "villa interior design Gachibowli",
  "flat interior design Gachibowli", "duplex interior design Gachibowli",
  "modular kitchen Gachibowli", "modular kitchen designer Gachibowli",
  "kitchen design Gachibowli", "kitchen renovation Gachibowli",
  "L shaped kitchen Gachibowli", "U shaped kitchen Gachibowli", "island kitchen Gachibowli",
  "false ceiling Gachibowli", "gypsum ceiling Gachibowli", "POP ceiling Gachibowli",
  "false ceiling designer Gachibowli", "ceiling design Gachibowli",
  "wardrobe designer Gachibowli", "walk-in wardrobe Gachibowli",
  "sliding wardrobe Gachibowli", "cupboard design Gachibowli", "built-in wardrobe Gachibowli",
  "home automation Gachibowli", "smart home Gachibowli", "smart lighting Gachibowli",
  "home theater Gachibowli", "home theater design Gachibowli",
  "main door design Gachibowli", "main door elevation Gachibowli",
  "full home renovation Gachibowli", "home renovation Gachibowli",
  "interior design consultation Gachibowli", "free consultation interior design Gachibowli",
  "interior decorator Gachibowli", "interior design studio Gachibowli",
  "renovation contractor Gachibowli", "3D interior design Gachibowli",
  "interior design price Gachibowli", "best interior design company Gachibowli",
  "luxury home interior Gachibowli", "bespoke interior design Gachibowli",
  "contemporary interior design Gachibowli", "modern interior design Gachibowli",
  "interior design quote Gachibowli", "pest control Gachibowli",
  "interior design cost Gachibowli", "top 10 interior designers Gachibowli",

  // ════════════════════════════════════════════════════════════════════════════
  // ── KONDAPUR ──
  // ════════════════════════════════════════════════════════════════════════════
  "interior designer Kondapur", "interior design Kondapur",
  "best interior designer Kondapur", "top interior designer Kondapur",
  "interior designer near me Kondapur", "interior design company Kondapur",
  "home interior design Kondapur", "luxury interior design Kondapur",
  "premium interior design Kondapur", "turnkey interior design Kondapur",
  "residential interior designer Kondapur", "commercial interior designer Kondapur",
  "office interior design Kondapur", "apartment interior design Kondapur",
  "2BHK interior design Kondapur", "3BHK interior design Kondapur",
  "4BHK interior design Kondapur", "villa interior design Kondapur",
  "flat interior design Kondapur", "duplex interior design Kondapur",
  "modular kitchen Kondapur", "modular kitchen designer Kondapur",
  "kitchen design Kondapur", "kitchen renovation Kondapur",
  "L shaped kitchen Kondapur", "U shaped kitchen Kondapur",
  "false ceiling Kondapur", "gypsum ceiling Kondapur", "POP ceiling Kondapur",
  "false ceiling designer Kondapur", "ceiling design Kondapur",
  "wardrobe designer Kondapur", "walk-in wardrobe Kondapur",
  "sliding wardrobe Kondapur", "cupboard design Kondapur", "built-in wardrobe Kondapur",
  "home automation Kondapur", "smart home Kondapur",
  "home theater Kondapur", "home theater design Kondapur",
  "main door design Kondapur", "main door elevation Kondapur",
  "full home renovation Kondapur", "home renovation Kondapur",
  "interior design consultation Kondapur", "free consultation interior design Kondapur",
  "interior decorator Kondapur", "interior design studio Kondapur",
  "renovation contractor Kondapur", "3D interior design Kondapur",
  "interior design price Kondapur", "best interior design Kondapur",
  "pest control Kondapur", "interior design cost Kondapur",

  // ════════════════════════════════════════════════════════════════════════════
  // ── NALLAGANDLA ──
  // ════════════════════════════════════════════════════════════════════════════
  "interior designer Nallagandla", "interior design Nallagandla",
  "best interior designer Nallagandla", "top interior designer Nallagandla",
  "interior designer near me Nallagandla", "interior design company Nallagandla",
  "home interior design Nallagandla", "luxury interior design Nallagandla",
  "premium interior design Nallagandla", "turnkey interior design Nallagandla",
  "residential interior designer Nallagandla", "commercial interior designer Nallagandla",
  "apartment interior design Nallagandla", "villa interior design Nallagandla",
  "2BHK interior design Nallagandla", "3BHK interior design Nallagandla",
  "modular kitchen Nallagandla", "modular kitchen designer Nallagandla",
  "kitchen design Nallagandla", "kitchen renovation Nallagandla",
  "false ceiling Nallagandla", "gypsum ceiling Nallagandla", "POP ceiling Nallagandla",
  "false ceiling designer Nallagandla", "ceiling design Nallagandla",
  "wardrobe designer Nallagandla", "walk-in wardrobe Nallagandla",
  "cupboard design Nallagandla", "built-in wardrobe Nallagandla",
  "home automation Nallagandla", "smart home Nallagandla",
  "home theater Nallagandla", "main door design Nallagandla",
  "full home renovation Nallagandla", "home renovation Nallagandla",
  "interior design consultation Nallagandla", "interior decorator Nallagandla",
  "renovation contractor Nallagandla", "interior design price Nallagandla",

  // ════════════════════════════════════════════════════════════════════════════
  // ── MIYAPUR ──
  // ════════════════════════════════════════════════════════════════════════════
  "interior designer Miyapur", "interior design Miyapur",
  "best interior designer Miyapur", "top interior designer Miyapur",
  "interior designer near me Miyapur", "interior design company Miyapur",
  "home interior design Miyapur", "luxury interior design Miyapur",
  "premium interior design Miyapur", "turnkey interior design Miyapur",
  "residential interior designer Miyapur", "commercial interior designer Miyapur",
  "office interior design Miyapur", "apartment interior design Miyapur",
  "2BHK interior design Miyapur", "3BHK interior design Miyapur",
  "4BHK interior design Miyapur", "villa interior design Miyapur",
  "flat interior design Miyapur", "duplex interior design Miyapur",
  "modular kitchen Miyapur", "modular kitchen designer Miyapur",
  "kitchen design Miyapur", "kitchen renovation Miyapur",
  "L shaped kitchen Miyapur", "U shaped kitchen Miyapur",
  "false ceiling Miyapur", "gypsum ceiling Miyapur", "POP ceiling Miyapur",
  "false ceiling designer Miyapur", "ceiling design Miyapur",
  "wardrobe designer Miyapur", "walk-in wardrobe Miyapur",
  "sliding wardrobe Miyapur", "cupboard design Miyapur", "built-in wardrobe Miyapur",
  "home automation Miyapur", "smart home Miyapur",
  "home theater Miyapur", "home theater design Miyapur",
  "main door design Miyapur", "main door elevation Miyapur",
  "full home renovation Miyapur", "home renovation Miyapur",
  "interior design consultation Miyapur", "free consultation interior design Miyapur",
  "interior decorator Miyapur", "interior design studio Miyapur",
  "renovation contractor Miyapur", "3D interior design Miyapur",
  "interior design price Miyapur", "best interior design Miyapur",
  "pest control Miyapur", "interior design cost Miyapur",

  // ════════════════════════════════════════════════════════════════════════════
  // ── BACHUPALLY ──
  // ════════════════════════════════════════════════════════════════════════════
  "interior designer Bachupally", "interior design Bachupally",
  "best interior designer Bachupally", "top interior designer Bachupally",
  "interior designer near me Bachupally", "interior design company Bachupally",
  "home interior design Bachupally", "luxury interior design Bachupally",
  "premium interior design Bachupally", "turnkey interior design Bachupally",
  "residential interior designer Bachupally", "commercial interior designer Bachupally",
  "office interior design Bachupally", "apartment interior design Bachupally",
  "2BHK interior design Bachupally", "3BHK interior design Bachupally",
  "villa interior design Bachupally", "flat interior design Bachupally",
  "modular kitchen Bachupally", "modular kitchen designer Bachupally",
  "kitchen design Bachupally", "kitchen renovation Bachupally",
  "false ceiling Bachupally", "gypsum ceiling Bachupally", "POP ceiling Bachupally",
  "false ceiling designer Bachupally", "ceiling design Bachupally",
  "wardrobe designer Bachupally", "walk-in wardrobe Bachupally",
  "cupboard design Bachupally", "built-in wardrobe Bachupally",
  "home automation Bachupally", "smart home Bachupally",
  "home theater Bachupally", "home theater design Bachupally",
  "main door design Bachupally", "main door elevation Bachupally",
  "full home renovation Bachupally", "home renovation Bachupally",
  "interior design consultation Bachupally", "interior decorator Bachupally",
  "renovation contractor Bachupally", "3D interior design Bachupally",
  "interior design price Bachupally", "pest control Bachupally",

  // ════════════════════════════════════════════════════════════════════════════
  // ── MEDCHAL ──
  // ════════════════════════════════════════════════════════════════════════════
  "interior designer Medchal", "interior design Medchal",
  "best interior designer Medchal", "top interior designer Medchal",
  "interior designer near me Medchal", "interior design company Medchal",
  "home interior design Medchal", "luxury interior design Medchal",
  "residential interior designer Medchal", "commercial interior designer Medchal",
  "apartment interior design Medchal", "villa interior design Medchal",
  "2BHK interior design Medchal", "3BHK interior design Medchal",
  "modular kitchen Medchal", "modular kitchen designer Medchal",
  "kitchen design Medchal", "false ceiling Medchal", "gypsum ceiling Medchal",
  "false ceiling designer Medchal", "ceiling design Medchal",
  "wardrobe designer Medchal", "cupboard design Medchal",
  "home automation Medchal", "home theater Medchal",
  "full home renovation Medchal", "home renovation Medchal",
  "interior design consultation Medchal", "interior decorator Medchal",
  "renovation contractor Medchal", "interior design price Medchal",
  "turnkey interior design Medchal", "premium interior design Medchal",

  // ════════════════════════════════════════════════════════════════════════════
  // ── MANIKONDA ──
  // ════════════════════════════════════════════════════════════════════════════
  "interior designer Manikonda", "interior design Manikonda",
  "best interior designer Manikonda", "top interior designer Manikonda",
  "interior designer near me Manikonda", "interior design company Manikonda",
  "home interior design Manikonda", "luxury interior design Manikonda",
  "premium interior design Manikonda", "turnkey interior design Manikonda",
  "residential interior designer Manikonda", "commercial interior designer Manikonda",
  "office interior design Manikonda", "apartment interior design Manikonda",
  "2BHK interior design Manikonda", "3BHK interior design Manikonda",
  "villa interior design Manikonda", "flat interior design Manikonda",
  "modular kitchen Manikonda", "modular kitchen designer Manikonda",
  "kitchen design Manikonda", "kitchen renovation Manikonda",
  "false ceiling Manikonda", "gypsum ceiling Manikonda", "POP ceiling Manikonda",
  "false ceiling designer Manikonda", "ceiling design Manikonda",
  "wardrobe designer Manikonda", "walk-in wardrobe Manikonda",
  "cupboard design Manikonda", "built-in wardrobe Manikonda",
  "home automation Manikonda", "smart home Manikonda",
  "home theater Manikonda", "home theater design Manikonda",
  "main door design Manikonda", "main door elevation Manikonda",
  "full home renovation Manikonda", "home renovation Manikonda",
  "interior design consultation Manikonda", "interior decorator Manikonda",
  "renovation contractor Manikonda", "interior design price Manikonda",
  "pest control Manikonda",

  // ════════════════════════════════════════════════════════════════════════════
  // ── RAIDURG ──
  // ════════════════════════════════════════════════════════════════════════════
  "interior designer Raidurg", "interior design Raidurg",
  "best interior designer Raidurg", "top interior designer Raidurg",
  "interior designer near me Raidurg", "interior design company Raidurg",
  "home interior design Raidurg", "luxury interior design Raidurg",
  "premium interior design Raidurg", "turnkey interior design Raidurg",
  "residential interior designer Raidurg", "commercial interior designer Raidurg",
  "office interior design Raidurg", "apartment interior design Raidurg",
  "2BHK interior design Raidurg", "3BHK interior design Raidurg",
  "villa interior design Raidurg", "flat interior design Raidurg",
  "modular kitchen Raidurg", "modular kitchen designer Raidurg",
  "kitchen design Raidurg", "kitchen renovation Raidurg",
  "false ceiling Raidurg", "gypsum ceiling Raidurg", "POP ceiling Raidurg",
  "false ceiling designer Raidurg", "ceiling design Raidurg",
  "wardrobe designer Raidurg", "walk-in wardrobe Raidurg",
  "cupboard design Raidurg", "home automation Raidurg",
  "home theater Raidurg", "main door design Raidurg",
  "full home renovation Raidurg", "home renovation Raidurg",
  "interior design consultation Raidurg", "interior decorator Raidurg",
  "renovation contractor Raidurg", "interior design price Raidurg",

  // ════════════════════════════════════════════════════════════════════════════
  // ── MADHAPUR ──
  // ════════════════════════════════════════════════════════════════════════════
  "interior designer Madhapur", "interior design Madhapur",
  "best interior designer Madhapur", "top interior designer Madhapur",
  "interior designer near me Madhapur", "interior design company Madhapur",
  "home interior design Madhapur", "luxury interior design Madhapur",
  "premium interior design Madhapur", "turnkey interior design Madhapur",
  "residential interior designer Madhapur", "commercial interior designer Madhapur",
  "office interior design Madhapur", "apartment interior design Madhapur",
  "2BHK interior design Madhapur", "3BHK interior design Madhapur",
  "4BHK interior design Madhapur", "villa interior design Madhapur",
  "flat interior design Madhapur", "duplex interior design Madhapur",
  "modular kitchen Madhapur", "modular kitchen designer Madhapur",
  "kitchen design Madhapur", "kitchen renovation Madhapur",
  "L shaped kitchen Madhapur", "U shaped kitchen Madhapur", "island kitchen Madhapur",
  "false ceiling Madhapur", "gypsum ceiling Madhapur", "POP ceiling Madhapur",
  "false ceiling designer Madhapur", "ceiling design Madhapur",
  "wardrobe designer Madhapur", "walk-in wardrobe Madhapur",
  "sliding wardrobe Madhapur", "cupboard design Madhapur", "built-in wardrobe Madhapur",
  "home automation Madhapur", "smart home Madhapur", "smart lighting Madhapur",
  "home theater Madhapur", "home theater design Madhapur",
  "main door design Madhapur", "main door elevation Madhapur",
  "full home renovation Madhapur", "home renovation Madhapur",
  "interior design consultation Madhapur", "free consultation interior design Madhapur",
  "interior decorator Madhapur", "interior design studio Madhapur",
  "renovation contractor Madhapur", "3D interior design Madhapur",
  "interior design price Madhapur", "best interior design company Madhapur",
  "luxury home interior Madhapur", "pest control Madhapur",
  "interior design cost Madhapur", "corporate interior design Madhapur",

  // ════════════════════════════════════════════════════════════════════════════
  // ── HITEC CITY ──
  // ════════════════════════════════════════════════════════════════════════════
  "interior designer HITEC City", "interior design HITEC City",
  "best interior designer HITEC City", "top interior designer HITEC City",
  "interior designer near me HITEC City", "interior design company HITEC City",
  "interior designer HiTech City", "interior design HiTech City",
  "interior designer Hitech City Hyderabad", "interior design Hitech City Hyderabad",
  "home interior design HITEC City", "luxury interior design HITEC City",
  "premium interior design HITEC City", "turnkey interior design HITEC City",
  "residential interior designer HITEC City", "commercial interior designer HITEC City",
  "office interior design HITEC City", "corporate interior design HITEC City",
  "apartment interior design HITEC City", "2BHK interior design HITEC City",
  "3BHK interior design HITEC City", "villa interior design HITEC City",
  "flat interior design HITEC City", "duplex interior design HITEC City",
  "modular kitchen HITEC City", "modular kitchen designer HITEC City",
  "kitchen design HITEC City", "kitchen renovation HITEC City",
  "false ceiling HITEC City", "gypsum ceiling HITEC City", "POP ceiling HITEC City",
  "false ceiling designer HITEC City", "ceiling design HITEC City",
  "wardrobe designer HITEC City", "walk-in wardrobe HITEC City",
  "sliding wardrobe HITEC City", "cupboard design HITEC City",
  "home automation HITEC City", "smart home HITEC City",
  "home theater HITEC City", "home theater design HITEC City",
  "main door design HITEC City", "main door elevation HITEC City",
  "full home renovation HITEC City", "home renovation HITEC City",
  "interior design consultation HITEC City", "interior decorator HITEC City",
  "renovation contractor HITEC City", "3D interior design HITEC City",
  "interior design price HITEC City", "pest control HITEC City",
  "office fit-out HITEC City", "office fit out HITEC City",
  "startup office design HITEC City", "co-working interior HITEC City",
  "corporate office interior HITEC City",

  // ════════════════════════════════════════════════════════════════════════════
  // ── KOKAPET ──
  // ════════════════════════════════════════════════════════════════════════════
  "interior designer Kokapet", "interior design Kokapet",
  "best interior designer Kokapet", "top interior designer Kokapet",
  "interior designer near me Kokapet", "interior design company Kokapet",
  "home interior design Kokapet", "luxury interior design Kokapet",
  "premium interior design Kokapet", "turnkey interior design Kokapet",
  "residential interior designer Kokapet", "commercial interior designer Kokapet",
  "apartment interior design Kokapet", "villa interior design Kokapet",
  "2BHK interior design Kokapet", "3BHK interior design Kokapet",
  "4BHK interior design Kokapet", "flat interior design Kokapet",
  "duplex interior design Kokapet", "penthouse interior design Kokapet",
  "modular kitchen Kokapet", "modular kitchen designer Kokapet",
  "kitchen design Kokapet", "kitchen renovation Kokapet",
  "L shaped kitchen Kokapet", "U shaped kitchen Kokapet",
  "false ceiling Kokapet", "gypsum ceiling Kokapet", "POP ceiling Kokapet",
  "false ceiling designer Kokapet", "ceiling design Kokapet",
  "wardrobe designer Kokapet", "walk-in wardrobe Kokapet",
  "sliding wardrobe Kokapet", "cupboard design Kokapet", "built-in wardrobe Kokapet",
  "home automation Kokapet", "smart home Kokapet",
  "home theater Kokapet", "home theater design Kokapet",
  "main door design Kokapet", "main door elevation Kokapet",
  "full home renovation Kokapet", "home renovation Kokapet",
  "interior design consultation Kokapet", "interior decorator Kokapet",
  "renovation contractor Kokapet", "3D interior design Kokapet",
  "interior design price Kokapet", "best interior design Kokapet",
  "pest control Kokapet", "luxury apartment interior Kokapet",

  // ════════════════════════════════════════════════════════════════════════════
  // ── SERVICE × CITY (cross-product) ──
  // ════════════════════════════════════════════════════════════════════════════

  // Modular kitchens — all 14 areas already covered above plus extras:
  "modular kitchen Hyderabad", "modular kitchen designer Hyderabad",
  "modular kitchen cost Hyderabad", "modular kitchen price Hyderabad",
  "modular kitchen installation Hyderabad", "modular kitchen renovation Hyderabad",
  "best modular kitchen Hyderabad", "modular kitchen company Hyderabad",
  "modular kitchen near me Hyderabad", "modular kitchen Gachibowli",
  "modular kitchen Nallagandla", "modular kitchen Nanakaramguda",
  "modular kitchen Tellapur", "modular kitchen Financial District",
  "modular kitchen Raidurg", "modular kitchen Medchal", "modular kitchen Kokapet",
  "L shaped modular kitchen Hyderabad", "U shaped modular kitchen Hyderabad",
  "island kitchen Hyderabad", "parallel kitchen Hyderabad", "straight kitchen Hyderabad",
  "high gloss kitchen Hyderabad", "matte finish kitchen Hyderabad",
  "acrylic modular kitchen Hyderabad", "laminate modular kitchen Hyderabad",
  "PVC modular kitchen Hyderabad", "wooden modular kitchen Hyderabad",
  "kitchen with breakfast counter Hyderabad", "open kitchen design Hyderabad",
  "kitchen pantry design Hyderabad", "kitchen with dining Hyderabad",

  // False ceiling — all areas + extras:
  "false ceiling Hyderabad", "gypsum ceiling Hyderabad", "POP ceiling Hyderabad",
  "false ceiling designer Hyderabad", "ceiling design Hyderabad",
  "LED ceiling Hyderabad", "cove ceiling Hyderabad", "coffered ceiling Hyderabad",
  "baffle ceiling Hyderabad", "stretch ceiling Hyderabad", "tray ceiling Hyderabad",
  "false ceiling cost Hyderabad", "false ceiling price Hyderabad",
  "false ceiling installation Hyderabad", "false ceiling contractor Hyderabad",
  "false ceiling near me Hyderabad", "ceiling design with lights Hyderabad",
  "false ceiling Nallagandla", "false ceiling Nanakaramguda",
  "false ceiling Tellapur", "false ceiling Financial District",
  "false ceiling Raidurg", "false ceiling Medchal", "false ceiling Kokapet",

  // Wardrobes — all areas + extras:
  "wardrobe designer Hyderabad", "walk-in wardrobe Hyderabad",
  "sliding wardrobe Hyderabad", "built-in wardrobe Hyderabad",
  "cupboard design Hyderabad", "wardrobe cost Hyderabad", "wardrobe price Hyderabad",
  "wardrobe renovation Hyderabad", "wardrobe installation Hyderabad",
  "wardrobe with mirror Hyderabad", "loft wardrobe Hyderabad",
  "kids wardrobe Hyderabad", "master bedroom wardrobe Hyderabad",
  "wardrobe designer Nallagandla", "wardrobe designer Nanakaramguda",
  "wardrobe designer Tellapur", "wardrobe designer Financial District",
  "wardrobe designer Raidurg", "wardrobe designer Medchal", "wardrobe designer Kokapet",
  "wardrobe designer Bachupally", "wardrobe designer Manikonda",

  // Office interiors — all areas + extras:
  "office interior design Hyderabad", "corporate interior design Hyderabad",
  "office fit-out Hyderabad", "office renovation Hyderabad",
  "office design company Hyderabad", "startup office design Hyderabad",
  "co-working space design Hyderabad", "office cabin design Hyderabad",
  "office ceiling design Hyderabad", "office flooring Hyderabad",
  "reception design Hyderabad", "conference room design Hyderabad",
  "office interior Gachibowli", "office interior Madhapur",
  "office interior HITEC City", "office interior Financial District",
  "office interior Kondapur", "office interior Raidurg",
  "office interior Nanakaramguda", "office interior Kokapet",
  "office interior Tellapur", "office interior Miyapur",
  "office interior Bachupally", "office interior Medchal",

  // Home automation — all areas + extras:
  "home automation Hyderabad", "smart home Hyderabad",
  "smart home installation Hyderabad", "home automation company Hyderabad",
  "smart lighting Hyderabad", "automated blinds Hyderabad",
  "home security system Hyderabad", "HVAC automation Hyderabad",
  "voice control home Hyderabad", "app controlled home Hyderabad",
  "Alexa home automation Hyderabad", "Google home automation Hyderabad",
  "home automation Nallagandla", "home automation Nanakaramguda",
  "home automation Tellapur", "home automation Financial District",
  "home automation Raidurg", "home automation Medchal", "home automation Kokapet",
  "home automation Bachupally", "home automation Manikonda",

  // Home theater — all areas + extras:
  "home theater design Hyderabad", "home cinema Hyderabad",
  "home theater installation Hyderabad", "home theater company Hyderabad",
  "4K projector installation Hyderabad", "surround sound system Hyderabad",
  "acoustic room design Hyderabad", "home theater room design Hyderabad",
  "home theater cost Hyderabad", "home theater price Hyderabad",
  "TV unit design Hyderabad", "entertainment wall design Hyderabad",
  "media room design Hyderabad", "AV system Hyderabad",
  "home theater Nallagandla", "home theater Nanakaramguda",
  "home theater Tellapur", "home theater Financial District",
  "home theater Raidurg", "home theater Medchal", "home theater Kokapet",

  // Main door elevation:
  "main door elevation Hyderabad", "main door design Hyderabad",
  "main entrance design Hyderabad", "door cladding Hyderabad",
  "wooden door design Hyderabad", "steel door design Hyderabad",
  "main door elevation cost Hyderabad", "main door elevation Gachibowli",
  "main door elevation Madhapur", "main door elevation HITEC City",
  "main door elevation Kondapur", "main door elevation Miyapur",
  "main door elevation Bachupally", "main door elevation Kokapet",

  // Renovation — all areas + extras:
  "full home renovation Hyderabad", "home renovation Hyderabad",
  "renovation contractor Hyderabad", "home remodelling Hyderabad",
  "house renovation Hyderabad", "flat renovation Hyderabad",
  "apartment renovation Hyderabad", "renovation cost Hyderabad",
  "renovation price Hyderabad", "interior renovation company Hyderabad",
  "bathroom renovation Hyderabad", "bedroom renovation Hyderabad",
  "living room renovation Hyderabad", "kitchen renovation Hyderabad",
  "home renovation Nallagandla", "home renovation Nanakaramguda",
  "home renovation Tellapur", "home renovation Financial District",
  "home renovation Raidurg", "home renovation Medchal", "home renovation Kokapet",

  // 3D visualisation:
  "3D interior design Hyderabad", "3D visualisation Hyderabad",
  "3D rendering interior design Hyderabad", "interior 3D design Gachibowli",
  "interior 3D design Madhapur", "interior 3D design HITEC City",
  "interior 3D design Kondapur", "interior 3D design Miyapur",

  // Pest control:
  "pest control Hyderabad", "pest control service Hyderabad",
  "residential pest control Hyderabad", "commercial pest control Hyderabad",
  "general pest control Gachibowli", "pest control Madhapur",
  "pest control HITEC City", "pest control Kondapur",

  // ── Central / premium Hyderabad ──
  "interior designer Banjara Hills", "interior design Banjara Hills",
  "best interior designer Banjara Hills", "modular kitchen Banjara Hills",
  "interior designer Jubilee Hills", "interior design Jubilee Hills",
  "best interior designer Jubilee Hills", "modular kitchen Jubilee Hills",
  "interior designer Begumpet", "interior design Begumpet",
  "interior designer Himayatnagar", "interior designer Panjagutta",
  "interior designer Somajiguda", "interior designer Kukatpally",
  "interior design Kukatpally", "modular kitchen Kukatpally",
  "interior designer Serilingampally", "interior design Serilingampally",
  "interior designer Narsingi", "interior design Narsingi",
  "interior designer Attapur", "interior designer Chandanagar",
  "interior designer Hafeezpet", "interior designer Puppalaguda",

  // ── East / South Hyderabad ──
  "interior designer LB Nagar", "interior design LB Nagar",
  "best interior designer LB Nagar", "modular kitchen LB Nagar",
  "interior designer Nagole", "interior design Nagole",
  "modular kitchen Nagole", "home renovation Nagole",
  "interior designer Uppal", "interior design Uppal",
  "modular kitchen Uppal", "home renovation Uppal",
  "interior designer Saroornagar", "interior design Saroornagar",
  "interior designer Kothapet", "interior design Kothapet",
  "modular kitchen Kothapet", "home renovation Kothapet",
  "interior designer Dilsukhnagar", "interior design Dilsukhnagar",
  "interior designer Kompally", "interior designer Bowenpally",
  "interior designer Secunderabad", "interior design Secunderabad",
  "interior designer Ameerpet", "interior designer SR Nagar",

  // ── Long-tail / question-based keywords (GEO-optimised) ──
  "how much does interior design cost in Hyderabad",
  "best interior designer in Hyderabad for 3BHK",
  "which is the best interior design company in Hyderabad",
  "top rated interior designers in Gachibowli Hyderabad",
  "interior designer for new flat in Hyderabad",
  "interior design for 2BHK apartment Hyderabad",
  "turnkey interior design Hyderabad price",
  "modular kitchen cost in Hyderabad 2024",
  "modular kitchen cost in Hyderabad 2025",
  "false ceiling cost in Hyderabad",
  "wardrobe cost in Hyderabad",
  "home theater cost in Hyderabad",
  "home automation cost in Hyderabad",
  "how to choose interior designer in Hyderabad",
  "interior designer for villa in Gachibowli",
  "interior designer for apartment in Madhapur",
  "office interior design cost in Hyderabad",
  "best modular kitchen brand in Hyderabad",
  "interior designer Hyderabad free consultation",
  "interior design near HITEC City",
  "interior design near Financial District",
  "interior design near Kondapur",
  "interior design near Kokapet",
  "interior design near Miyapur",

  // ── State / region ──
  "interior design Telangana", "premium interior design Telangana",
  "best interior designer Telangana", "interior design company Telangana",
];

const BASE_DESCRIPTION =
  "Vinay Interiors — Hyderabad's premium interior design & architecture studio since 2014. Modular kitchens, wardrobes, false ceilings, office interiors & home automation. Serving Gachibowli, Madhapur, HITEC City, Kondapur, Manikonda, Miyapur, Bachupally, Tellapur, Financial District, Nanakaramguda, Nallagandla & all of Hyderabad. 200+ projects. Free consultation.";

const OG_IMAGE =
  "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=1200&h=630";

// ─── Default (root layout) metadata ─────────────────────────────────────────
export const defaultMetadata: Metadata = {
  metadataBase: new URL(SITE.siteUrl),
  title: {
    default: `${SITE.name} | Best Interior Designer Hyderabad – Gachibowli, Madhapur, Kondapur, Miyapur`,
    template: `%s | ${SITE.name}`,
  },
  description: BASE_DESCRIPTION,
  keywords: KEYWORDS,
  authors: [{ name: SITE.name, url: SITE.siteUrl }],
  icons: {
    icon: "/Untitled design.png",
    shortcut: "/Untitled design.png",
    apple: "/Untitled design.png",
  },
  creator: SITE.name,
  publisher: SITE.name,
  category: "Interior Design",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  openGraph: {
    type: "website",
    locale: "en_IN",
    url: SITE.siteUrl,
    siteName: SITE.name,
    title: `${SITE.name} | Best Interior Designer Hyderabad`,
    description: BASE_DESCRIPTION,
    images: [{ url: OG_IMAGE, width: 1200, height: 630, alt: `${SITE.name} — luxury interior design and architecture studio in Hyderabad, Telangana, India` }],
  },
  twitter: {
    card: "summary_large_image",
    site: "@vinayinteriors",
    creator: "@vinayinteriors",
    title: `${SITE.name} | Interior Designer Hyderabad`,
    description: BASE_DESCRIPTION,
    images: [{ url: OG_IMAGE, alt: `${SITE.name} — bespoke interior design and architecture, Hyderabad` }],
  },
  alternates: { canonical: "/" },
  other: {
    "geo.region": "IN-TG",
    "geo.placename": "Hyderabad, Telangana, India",
    "geo.position": "17.3850;78.4867",
    "ICBM": "17.3850, 78.4867",
    "coverage": "Gachibowli, Madhapur, HITEC City, Raidurg, Kondapur, Kokapet, Nanakaramguda, Financial District, Tellapur, Miyapur, Bachupally, Medchal, Nallagandla, Manikonda, LB Nagar, Nagole, Uppal, Saroornagar, Kothapet, Hyderabad, Telangana",
    "classification": "Interior Design, Architecture, Home Renovation",
    "language": "English",
    "revisit-after": "7 days",
    "rating": "general",
    "DC.language": "en-IN",
    "DC.coverage": "Hyderabad, Telangana, India",
    "DC.subject": "Interior Design, Architecture, Home Renovation, Hyderabad",
  },
};

// ─── Per-page metadata builder ───────────────────────────────────────────────
type SeoProps = {
  title: string;
  description: string;
  path?: string;
  image?: string;
  keywords?: string[];
};

export const buildMetadata = ({ title, description, path = "/", image = OG_IMAGE, keywords }: SeoProps): Metadata => ({
  title,
  description,
  keywords: keywords ?? KEYWORDS,
  alternates: { canonical: path },
  openGraph: {
    title: `${title} | ${SITE.name}`,
    description,
    url: `${SITE.siteUrl}${path}`,
    images: [{ url: image, width: 1200, height: 630, alt: `${title} — ${SITE.name}, Interior Design Studio Hyderabad` }],
  },
  twitter: {
    title: `${title} | ${SITE.name}`,
    description,
    images: [image],
  },
  other: {
    "geo.region": "IN-TG",
    "geo.placename": "Hyderabad, Telangana, India",
    "geo.position": "17.3850;78.4867",
    "ICBM": "17.3850, 78.4867",
    "coverage": "Gachibowli, Madhapur, HITEC City, Raidurg, Kondapur, Nanakaramguda, Financial District, Tellapur, Miyapur, Bachupally, Medchal, Nallagandla, Manikonda, LB Nagar, Nagole, Uppal, Saroornagar, Kothapet, Hyderabad",
    "classification": "Interior Design, Architecture",
    "language": "English",
  },
});

// ─── WebSite JSON-LD ─────────────────────────────────────────────────────────
export const websiteJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  "@id": `${SITE.siteUrl}/#website`,
  url: SITE.siteUrl,
  name: SITE.name,
  description: BASE_DESCRIPTION,
  inLanguage: "en-IN",
  publisher: { "@id": `${SITE.siteUrl}/#organization` },
  // Sitelinks SearchBox — helps Google/AI surface a search directly in results
  potentialAction: {
    "@type": "SearchAction",
    target: {
      "@type": "EntryPoint",
      urlTemplate: `${SITE.siteUrl}/projects?q={search_term_string}`,
    },
    "query-input": "required name=search_term_string",
  },
};

// ─── Organization / LocalBusiness JSON-LD ───────────────────────────────────
export const organizationJsonLd = {
  "@context": "https://schema.org",
  "@type": ["InteriorDesignCompany", "LocalBusiness", "HomeAndConstructionBusiness"],
  "@id": `${SITE.siteUrl}/#organization`,
  name: SITE.legalName,
  alternateName: ["Vinay Interiors", "Vinay Atelier", "Vinay Interiors Hyderabad"],
  url: SITE.siteUrl,
  email: SITE.email,
  telephone: SITE.phone,
  foundingDate: "2014",
  description: BASE_DESCRIPTION,
  image: OG_IMAGE,
  logo: {
    "@type": "ImageObject",
    url: `${SITE.siteUrl}/logo.webp`,
    width: 400,
    height: 200,
  },
  priceRange: "₹₹₹",
  openingHoursSpecification: [
    {
      "@type": "OpeningHoursSpecification",
      dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
      opens: "09:00",
      closes: "20:00",
    },
  ],
  paymentAccepted: "Cash, Bank Transfer, UPI, Cheque",
  currenciesAccepted: "INR",
  address: {
    "@type": "PostalAddress",
    streetAddress: "Gachibowli",
    addressLocality: "Hyderabad",
    addressRegion: "Telangana",
    postalCode: "500032",
    addressCountry: "IN",
  },
  additionalProperty: [
    {
      "@type": "PropertyValue",
      name: "Factory Address",
      value: "House No. 3-100/3, Alinagar, Chetlapotharam Village, Gaddapotharam Panchayat, Jinnaram Mandal, Sangareddy District, Hyderabad, Telangana – 502319",
    },
    {
      "@type": "PropertyValue",
      name: "llms.txt",
      value: "https://vinayatelier.com/llms.txt",
    },
  ],
  geo: { "@type": "GeoCoordinates", latitude: "17.3850", longitude: "78.4867" },
  areaServed: [
    { "@type": "City", name: "Hyderabad", sameAs: "https://en.wikipedia.org/wiki/Hyderabad" },
    { "@type": "Neighborhood", name: "Gachibowli", containedInPlace: "Hyderabad" },
    { "@type": "Neighborhood", name: "Madhapur", containedInPlace: "Hyderabad" },
    { "@type": "Neighborhood", name: "HITEC City", containedInPlace: "Hyderabad" },
    { "@type": "Neighborhood", name: "Raidurg", containedInPlace: "Hyderabad" },
    { "@type": "Neighborhood", name: "Kondapur", containedInPlace: "Hyderabad" },
    { "@type": "Neighborhood", name: "Kokapet", containedInPlace: "Hyderabad" },
    { "@type": "Neighborhood", name: "Nanakaramguda", containedInPlace: "Hyderabad" },
    { "@type": "Neighborhood", name: "Financial District", containedInPlace: "Hyderabad" },
    { "@type": "Neighborhood", name: "Tellapur", containedInPlace: "Hyderabad" },
    { "@type": "Neighborhood", name: "Miyapur", containedInPlace: "Hyderabad" },
    { "@type": "Neighborhood", name: "Bachupally", containedInPlace: "Hyderabad" },
    { "@type": "Neighborhood", name: "Medchal", containedInPlace: "Hyderabad" },
    { "@type": "Neighborhood", name: "Nallagandla", containedInPlace: "Hyderabad" },
    { "@type": "Neighborhood", name: "Manikonda", containedInPlace: "Hyderabad" },
    { "@type": "Neighborhood", name: "Narsingi", containedInPlace: "Hyderabad" },
    { "@type": "Neighborhood", name: "Serilingampally", containedInPlace: "Hyderabad" },
    { "@type": "Neighborhood", name: "Banjara Hills", containedInPlace: "Hyderabad" },
    { "@type": "Neighborhood", name: "Jubilee Hills", containedInPlace: "Hyderabad" },
    { "@type": "Neighborhood", name: "Begumpet", containedInPlace: "Hyderabad" },
    { "@type": "Neighborhood", name: "Dilsukhnagar", containedInPlace: "Hyderabad" },
    { "@type": "Neighborhood", name: "LB Nagar", containedInPlace: "Hyderabad" },
    { "@type": "Neighborhood", name: "Nagole", containedInPlace: "Hyderabad" },
    { "@type": "Neighborhood", name: "Uppal", containedInPlace: "Hyderabad" },
    { "@type": "Neighborhood", name: "Saroornagar", containedInPlace: "Hyderabad" },
    { "@type": "Neighborhood", name: "Kothapet", containedInPlace: "Hyderabad" },
  ],
  hasOfferCatalog: {
    "@type": "OfferCatalog",
    name: "Interior Design & Architecture Services",
    itemListElement: [
      { "@type": "Offer", itemOffered: { "@type": "Service", name: "Modular Kitchen Design", areaServed: "Hyderabad", description: "Contemporary modular kitchens for Hyderabad homes — high-gloss lacquered shutters, textured laminates, easy to maintain. Serving Gachibowli, Madhapur, Kondapur, Miyapur, Bachupally, Manikonda, Financial District." } },
      { "@type": "Offer", itemOffered: { "@type": "Service", name: "Wardrobe & Cupboard Design", areaServed: "Hyderabad", description: "Walk-in wardrobes and built-in cupboards crafted to maximise space across Hyderabad residences including Gachibowli, Kondapur, Tellapur, Nallagandla." } },
      { "@type": "Offer", itemOffered: { "@type": "Service", name: "False Ceiling Design", areaServed: "Hyderabad", description: "Gypsum, POP and baffle ceiling systems with integrated ambient lighting for Hyderabad interiors. Available across Madhapur, HITEC City, Miyapur, Bachupally." } },
      { "@type": "Offer", itemOffered: { "@type": "Service", name: "Office Interior Design", areaServed: "Hyderabad", description: "Premium office interiors for Hyderabad's HITEC City, Gachibowli, Madhapur, Financial District and Raidurg businesses." } },
      { "@type": "Offer", itemOffered: { "@type": "Service", name: "Home Theater Design", areaServed: "Hyderabad", description: "Immersive home theater rooms with 4K projection and calibrated surround sound in Hyderabad." } },
      { "@type": "Offer", itemOffered: { "@type": "Service", name: "Home Automation", areaServed: "Hyderabad", description: "Smart home automation — lighting, HVAC, security, entertainment — for Hyderabad homes across Gachibowli, Madhapur, Kondapur, Miyapur." } },
      { "@type": "Offer", itemOffered: { "@type": "Service", name: "Main Door Elevation Design", areaServed: "Hyderabad", description: "Statement main door designs with premium hardware across Hyderabad." } },
      { "@type": "Offer", itemOffered: { "@type": "Service", name: "Full Home Renovation", areaServed: "Hyderabad", description: "Complete renovation services across Hyderabad — Gachibowli, Madhapur, Kondapur, Miyapur, Bachupally, Tellapur, Nanakaramguda, Financial District, Nallagandla, Manikonda and beyond." } },
      { "@type": "Offer", itemOffered: { "@type": "Service", name: "Residential Interior Design", areaServed: "Hyderabad", description: "Bespoke interior design for villas, apartments and independent houses across Hyderabad including all premium localities." } },
      { "@type": "Offer", itemOffered: { "@type": "Service", name: "Commercial Interior Design", areaServed: "Hyderabad", description: "End-to-end commercial interior design for offices, retail and hospitality venues in Hyderabad's business districts." } },
    ],
  },
  aggregateRating: { "@type": "AggregateRating", ratingValue: "4.9", reviewCount: "87", bestRating: "5", worstRating: "1" },
  sameAs: [SITE.social.instagram, SITE.social.behance, SITE.social.linkedin],
};

// ─── Breadcrumb JSON-LD helper ───────────────────────────────────────────────
export const breadcrumbJsonLd = (items: { name: string; url: string }[]) => ({
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: items.map((item, i) => ({
    "@type": "ListItem",
    position: i + 1,
    name: item.name,
    item: `${SITE.siteUrl}${item.url}`,
  })),
});

// ─── FAQ JSON-LD helper ──────────────────────────────────────────────────────
export const faqJsonLd = (items: { q: string; a: string }[]) => ({
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: items.map((item) => ({
    "@type": "Question",
    name: item.q,
    acceptedAnswer: { "@type": "Answer", text: item.a },
  })),
});

// ─── Speakable schema — marks content safe for AI/voice summarisation (GEO) ──
export const speakableJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebPage",
  "@id": `${SITE.siteUrl}/#webpage`,
  name: "Vinay Interiors — Best Interior Designer Hyderabad",
  description: BASE_DESCRIPTION,
  url: SITE.siteUrl,
  speakable: {
    "@type": "SpeakableSpecification",
    // Tell AI engines which CSS selectors contain the most quotable/answerable content
    cssSelector: ["h1", "h2", ".speakable"],
  },
  about: { "@id": `${SITE.siteUrl}/#organization` },
  mentions: [
    { "@type": "Place", name: "Gachibowli", containedInPlace: { "@type": "City", name: "Hyderabad" } },
    { "@type": "Place", name: "Madhapur", containedInPlace: { "@type": "City", name: "Hyderabad" } },
    { "@type": "Place", name: "HITEC City", containedInPlace: { "@type": "City", name: "Hyderabad" } },
    { "@type": "Place", name: "Financial District", containedInPlace: { "@type": "City", name: "Hyderabad" } },
    { "@type": "Place", name: "Kondapur", containedInPlace: { "@type": "City", name: "Hyderabad" } },
  ],
};

// ─── Homepage FAQ data (for rich snippets) ───────────────────────────────────
export const homepageFaqJsonLd = faqJsonLd([
  {
    q: "Who is the best interior designer in Hyderabad?",
    a: "Vinay Interiors is one of Hyderabad's most trusted interior design studios, with 12+ years of experience and 200+ completed projects across Gachibowli, Madhapur, HITEC City, Kondapur, Miyapur, Bachupally, Tellapur, Financial District, Nanakaramguda, Nallagandla, Manikonda and beyond. Call +91 9866618370 for a free consultation.",
  },
  {
    q: "What areas in Hyderabad does Vinay Interiors serve?",
    a: "Vinay Interiors serves all major localities in Hyderabad — with a primary focus on West Hyderabad including Gachibowli, Madhapur, HITEC City, Raidurg, Kondapur, Kokapet, Nanakaramguda, Financial District, Tellapur, Miyapur, Bachupally, Medchal, Nallagandla, Manikonda, Narsingi, and Serilingampally. We also serve Banjara Hills, Jubilee Hills, LB Nagar, Uppal, Nagole, Kothapet and the entire city.",
  },
  {
    q: "How much does interior design cost in Hyderabad?",
    a: "Interior design costs in Hyderabad depend on the size of the project, materials selected, and the scope of work. Vinay Interiors offers transparent pricing for modular kitchens, wardrobes, false ceilings, full home interiors, and office fit-outs. Contact us at +91 9866618370 for a free site visit and detailed quote.",
  },
  {
    q: "Do you offer free interior design consultation in Hyderabad?",
    a: "Yes, Vinay Interiors provides a free initial consultation and site visit across all areas in Hyderabad. Call +91 9866618370 or fill out our inquiry form to schedule a visit.",
  },
  {
    q: "What interior design services does Vinay Interiors offer?",
    a: "Vinay Interiors offers modular kitchen design, wardrobe & cupboard design, false ceiling design, office interiors, home theater design, main door elevation, home automation (smart home), pest control, and full turnkey interior design and renovation services across Hyderabad.",
  },
  {
    q: "Do you provide turnkey interior design projects in Hyderabad?",
    a: "Yes. Vinay Interiors handles the entire project from concept and 3D visualization to material procurement and on-site execution — delivering a fully finished, move-in-ready space. We serve clients in Gachibowli, Madhapur, HITEC City, Kondapur, Miyapur, Bachupally, Financial District, Tellapur, and all of Hyderabad.",
  },
  {
    q: "How long does a full home interior design project take in Hyderabad?",
    a: "A typical 3BHK interior design project in Hyderabad takes 45–90 days from finalised design to handover, depending on scope and material availability. Vinay Interiors maintains clear timelines and provides project updates at every stage.",
  },
  {
    q: "Can I get interior design done in the Financial District or Nanakaramguda, Hyderabad?",
    a: "Absolutely. Vinay Interiors actively serves both the Financial District and Nanakaramguda, two of our primary areas in West Hyderabad. We have completed multiple residential and commercial projects in these localities. Call +91 9866618370 to discuss your project.",
  },
  {
    q: "Does Vinay Interiors do office interior design in HITEC City and Madhapur?",
    a: "Yes. We specialise in premium office interiors for HITEC City, Madhapur, Gachibowli, Raidurg, and the Financial District — Hyderabad's primary tech and business corridors. Our office design work includes space planning, acoustic ceiling systems, workstation layouts, and brand-aligned finishes.",
  },
  {
    q: "What is the difference between modular and semi-modular kitchens?",
    a: "A modular kitchen uses pre-fabricated, factory-made cabinet modules that are assembled on-site, offering precision, uniformity, and easy future reconfiguration. A semi-modular kitchen combines some factory modules with custom-built components. Vinay Interiors designs and installs both types across Hyderabad — from Gachibowli and Kondapur to Miyapur and Bachupally.",
  },
]);
